name: 'Setup Environment'
description: 'Sets up the required JDKs and validates the Gradle wrapper'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          17
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b
